version: '3.8'

services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  db_test:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_test_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/cooking_time
    ports:
      - '3000:3000'
    depends_on:
      - db
      - db_test
    links:
      - db:db
      - db_test:db_test

volumes:
  db_data:
  db_test_data:
